title: Birinder Bachhal
description: Personal Portfolio
url: "https://bbachhal.github.io"
baseurl: "/personalportfolio"

remote_theme: ankitsultana/researcher@gem

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown

navbar:
  - title: Projects
    url: /projects/
  - title: Resume
    url: /resume/
  - title: Contact
    url: /contact/

footer: false
