url: "https://bbachhal.github.io"
baseurl: ""

remote_theme: ankitsultana/researcher@gem

plugins:
  - github-pages
  - jekyll-remote-theme
  - jekyll-seo-tag


tracking_id: #

footer: no
# footer_url: "https://github.com/bbachhal"
# footer_text: "Page design by Ankit Sultana"

# twitter_username: "bluh"
 
sass:
    style: compressed
    sass_dir: _sass
    
footer: no
