
title: Birinder Bachhal
url: "https://bbachhal.github.io/"
baseurl: ""

markdown: kramdown
ins_logo: "bu logo.png"

remote_theme: ankitsultana/researcher@gem

plugins:
- jekyll-remote-theme

tracking_id: #

footer: no
footer_url: "#ins-logo"
footer_text: "back to top"

# twitter_username: "bluh"
 
sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "projects"
   link: "#projects"
 - name: coursework
   link: "#coursework"
 - name: "resume"
   link: "Birinder Bachhal - Resume (2).pdf"
 - name: "contact"
   link: "contact"
